### ISSUE TITLE
Affinity Map created from user interview analysis

### ISSUE THREAD

**Issue by avantikajain289** [cncf/landscape#3277]
Add the consolidated figjam file link with the affinity diagram created by @hilzygift and @avantikajain289. @andreuxxxx please note.

```[tasklist]
### Tasks
- [ ] Create consolidated figjam file with CNCF email
- [ ] Add affinity map and any other analysis to the figjam file (hilda and avantika)
- [ ] Upload it on github to keep all assets in one place
```

**Comment by Hilzygift** [comment]
Hi @avantikajain289 @andreuxxxx 
Here's the affinity map [link](https://www.figma.com/file/KacZDK93huVIMlGKj2sarf/CNCF-Landscape-UX-UI-Improvement-1-(Research-Analysis)?type=whiteboard&node-id=0%3A1&t=HLIYsZPkQVSBE4j2-1)

**Comment by avantikajain289** [comment]
Figma File Showcasing the Affinity Diagram based on the devOps persona:

https://www.figma.com/file/UHnH3wdz5TBiCrKCFMKBD5/Affinity-Mapping%3A-Software-Developer%2FDevOps?type=whiteboard&node-id=0%3A1&t=2ulnARPKVR5OY410-1

**Comment by tegioz** [comment]
Thanks @avantikajain289!

We've just migrated the [CNCF landscape to v2](https://landscape.cncf.io), so I'll close this one for now.

Please feel free to reopen if needed 🙂
