### ISSUE TITLE
Hingga 

### ISSUE THREAD

**Issue by rohail0346khan** [cncf/landscape#3993]
Hi

Can you please review and approve PR for nOps entry? We need it today for KubeCon entry.

_Originally posted by @ajaviaad in https://github.com/cncf/landscape/issues/3989#issuecomment-2297117760_
            
```[tasklist]
### Tasks
- [ ] https://github.com/cncf/landscape/pull/3992
- [ ] https://github.com/cncf/landscape/pull/3989
- [ ] https://github.com/cncf/landscape/pull/3991
- [ ] https://github.com/cncf/landscape/pull/3984
- [ ] https://github.com/cncf/landscape/pull/3987
- [ ] https://github.com/cncf/landscape/pull/3990
- [ ] https://github.com/cncf/landscape/pull/3986
- [ ] https://github.com/cncf/landscape/pull/3979
- [ ] https://github.com/cncf/landscape/pull/3985
- [ ] https://github.com/cncf/landscape/pull/3988
- [ ] https://github.com/cncf/landscape/pull/3978
- [ ] https://github.com/cncf/landscape/pull/3982
- [ ] https://github.com/cncf/landscape/pull/3981
- [ ] https://github.com/cncf/landscape/pull/3983
```
